-- Create trips table for trip records
-- Stores trip information including tap in/out, location, and route details
CREATE TABLE IF NOT EXISTS trips (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    
    -- Trip Identification
    trip_id VARCHAR(50) NOT NULL COMMENT 'Trip ID generated by POS device (format: YYYYMMDDHHMMSS) - allows duplicates',
    
    -- Foreign Key References
    driver_assign_id INT UNSIGNED NOT NULL COMMENT 'Foreign key to device_assignments table (driver-device assignment)',
    route_id INT UNSIGNED NOT NULL COMMENT 'Foreign key to routes table',
    card_id VARCHAR(50) DEFAULT NULL COMMENT 'Card ID number from POS device (references cards.card_id_number)',
    
    -- Tap Information
    tap_level ENUM('IN', 'OUT') DEFAULT NULL COMMENT 'Tap in or tap out',
    
    -- Location Information
    longitude DECIMAL(11, 8) NOT NULL COMMENT 'Longitude coordinate',
    latitude DECIMAL(10, 8) NOT NULL COMMENT 'Latitude coordinate',
 

    
    -- Trip Details
    distance_km DECIMAL(10, 2) DEFAULT NULL COMMENT 'Actual distance traveled in kilometers (calculated from GPS or from route default)',
    fare_amount DECIMAL(10, 2) DEFAULT NULL COMMENT 'Fare amount for this trip',
    trip_status ENUM('pending', 'completed', 'cancelled','assisted') DEFAULT 'pending',
    
    -- Timestamps
    timestamp DATETIME NOT NULL COMMENT 'Exact time when the tap occurred',
    
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id),
    FOREIGN KEY (driver_assign_id) REFERENCES device_assignments(id) ON DELETE CASCADE,
    FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE,
    FOREIGN KEY (card_id) REFERENCES cards(card_id_number) ON DELETE CASCADE,
    INDEX idx_trip_id (trip_id),
    INDEX idx_driver_assign_id (driver_assign_id),
    INDEX idx_route_id (route_id),
    INDEX idx_card_id (card_id),
    INDEX idx_tap_level (tap_level),
    INDEX idx_timestamp (timestamp),
    INDEX idx_trip_status (trip_status),
    INDEX idx_location (latitude, longitude),
    INDEX idx_distance (distance_km)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

